// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKcydBqHObsh1_0t74nhLNug6oz2ohL3k',
    appId: '1:485126769574:web:ce877a9e4f7ee7be3add67',
    messagingSenderId: '485126769574',
    projectId: 'bigcareer-435be',
    authDomain: 'bigcareer-435be.firebaseapp.com',
    databaseURL: 'https://bigcareer-435be-default-rtdb.firebaseio.com',
    storageBucket: 'bigcareer-435be.appspot.com',
    measurementId: 'G-KD2DBWTEV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBugoCkWevWn5kROaFMAmNEbTjN3JJUfSc',
    appId: '1:485126769574:android:047bd5f326924a063add67',
    messagingSenderId: '485126769574',
    projectId: 'bigcareer-435be',
    databaseURL: 'https://bigcareer-435be-default-rtdb.firebaseio.com',
    storageBucket: 'bigcareer-435be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0klUmFCGtMuimCWpS-FA584GCdPPpLG0',
    appId: '1:485126769574:ios:4cb47d6b3152687c3add67',
    messagingSenderId: '485126769574',
    projectId: 'bigcareer-435be',
    databaseURL: 'https://bigcareer-435be-default-rtdb.firebaseio.com',
    storageBucket: 'bigcareer-435be.appspot.com',
    androidClientId: '485126769574-rjk9ce36qb4dluek5jga0p09hnlilgu6.apps.googleusercontent.com',
    iosClientId: '485126769574-k40fvt9ujsin9tvvk02rvtl8oa2gc939.apps.googleusercontent.com',
    iosBundleId: 'com.example.owsBigcareer',
  );
}
