var freelancersJson = [
  {
    "id": "1",
    "name": "Abhishekh Kumar",
    "image":'https://cdn5.vectorstock.com/i/1000x1000/24/09/remote-freelance-work-concept-man-freelancer-vector-30322409.jpg',
    "title": "Graphic Designer & Software Architect",
    "about":"Strong experience in Software Architecture & Graphic Design. Working with Angular 6 (backwards compatible as)",
    "rating": "5",
    "cost": "80",
    "currencyName": "USD",
    "currencySymbol": "dollar",
    "paymentMode": "hour",
    "like":'0',
    "skills": "PHP, Website Design, wordpress, eCommerce, html",
    "country":'India'
  },
  {
    "id":"2",
    "name": "Lalit Kumar",
    "image":'https://cdn3.vectorstock.com/i/1000x1000/73/22/freelancer-at-the-workplace-flat-vector-14947322.jpg',
    "title": "Software Developer and React Designer",
    "about":"Having good experience in software development, developed more then 20 projects including eCommerce, Food delivery, medical system etc",
    "rating": "4",
    "cost": "50",
    "currencyName": "INR",
    "currencySymbol": "₹",
    "paymentMode": "per hour",
    "like":'0',
    "skills": "Java, React Native , AWS, JSF",
    "country":'Australia'
  },
  {
    "id":"3",
    "name": "Abhishekh Kumar",
    "image":'https://cdn5.vectorstock.com/i/1000x1000/24/09/remote-freelance-work-concept-man-freelancer-vector-30322409.jpg',
    "title": "Graphic Designer & Software Architect",
    "about":"Strong experience in Software Architecture & Graphic Design. Working with Angular 6 (backwards compatible as)",
    "rating": "5",
    "cost": "80",
    "currencyName": "USD",
    "currencySymbol": "dollar",
    "paymentMode": "hour",
    "like":'0',
    "skills": "PHP, Website Design, wordpress, eCommerce, html",
    "country":'India'
  },
  {
    "id":"4",
    "name": "Lalit Kumar",
    "image":'https://cdn3.vectorstock.com/i/1000x1000/73/22/freelancer-at-the-workplace-flat-vector-14947322.jpg',
    "title": "Software Developer and React Designer",
    "about":"Having good experience in software development, developed more then 20 projects including eCommerce, Food delivery, medical system etc",
    "rating": "4",
    "cost": "50",
    "currencyName": "INR",
    "currencySymbol": "₹",
    "paymentMode": "hour",
    "like":'0',
    "skills": "Java, React Native , AWS, JSF",
    "country":'Australia'
  },
  {
    "id":"5",
    "name": "Abhishekh Kumar",
    "image":'https://cdn5.vectorstock.com/i/1000x1000/24/09/remote-freelance-work-concept-man-freelancer-vector-30322409.jpg',
    "title": "Graphic Designer & Software Architect",
    "about":"Strong experience in Software Architecture & Graphic Design. Working with Angular 6 (backwards compatible as)",
    "rating": "5",
    "cost": "80",
    "currencyName": "USD",
    "currencySymbol": "dollar",
    "paymentMode": "hour",
    "like":'0',
    "skills": "PHP, Website Design, wordpress, eCommerce, html",
    "country":'India'
  },
  {
    "id":"6",
    "name": "Lalit Kumar",
    "image":'https://cdn3.vectorstock.com/i/1000x1000/73/22/freelancer-at-the-workplace-flat-vector-14947322.jpg',
    "title": "Software Developer and React Designer",
    "about":"Having good experience in software development, developed more then 20 projects including eCommerce, Food delivery, medical system etc",
    "rating": "4",
    "cost": "50",
    "currencyName": "INR",
    "currencySymbol": "₹",
    "paymentMode": "hour",
    "like":'0',
    "skills": "Java, React Native , AWS, JSF",
    "country":'Australia'
  },
  {
    "id":"7",
    "name": "Abhishekh Kumar",
    "image":'https://cdn5.vectorstock.com/i/1000x1000/24/09/remote-freelance-work-concept-man-freelancer-vector-30322409.jpg',
    "title": "Graphic Designer & Software Architect",
    "about":"Strong experience in Software Architecture & Graphic Design. Working with Angular 6 (backwards compatible as)",
    "rating": "5",
    "cost": "80",
    "currencyName": "USD",
    "currencySymbol": "dollar",
    "paymentMode": "hour",
    "like":'0',
    "skills": "PHP, Website Design, wordpress, eCommerce, html",
    "country":'India'
  },
  {
    "id":"8",
    "name": "Lalit Kumar",
    "image":'https://cdn3.vectorstock.com/i/1000x1000/73/22/freelancer-at-the-workplace-flat-vector-14947322.jpg',
    "title": "Software Developer and React Designer",
    "about":"Having good experience in software development, developed more then 20 projects including eCommerce, Food delivery, medical system etc",
    "rating": "4",
    "cost": "50",
    "currencyName": "INR",
    "currencySymbol": "₹",
    "paymentMode": "hour",
    "like":'0',
    "skills": "Java, React Native , AWS, JSF",
    "country":'Australia'
  },
  {
    "id":"9",
    "name": "Abhishekh Kumar",
    "image":'https://cdn5.vectorstock.com/i/1000x1000/24/09/remote-freelance-work-concept-man-freelancer-vector-30322409.jpg',
    "title": "Graphic Designer & Software Architect",
    "about":"Strong experience in Software Architecture & Graphic Design. Working with Angular 6 (backwards compatible as)",
    "rating": "5",
    "cost": "80",
    "currencyName": "USD",
    "currencySymbol": "dollar",
    "paymentMode": "hour",
    "like":'0',
    "skills": "PHP, Website Design, wordpress, eCommerce, html",
    "country":'India'
  },
  {
    "id":"10",
    "name": "Lalit Kumar",
    "image":'https://cdn3.vectorstock.com/i/1000x1000/73/22/freelancer-at-the-workplace-flat-vector-14947322.jpg',
    "title": "Software Developer and React Designer",
    "about":"Having good experience in software development, developed more then 20 projects including eCommerce, Food delivery, medical system etc",
    "rating": "4",
    "cost": "50",
    "currencyName": "INR",
    "currencySymbol": "₹",
    "paymentMode": "hour",
    "like":'0',
    "skills": "Java, React Native , AWS, JSF",
    "country":'Australia'
  }
];